language: generic
env:
  - EVM_EMACS=emacs-25.1-travis
before_install:
  - ln -s $TRAVIS_BUILD_DIR ~/.emacs.d
  - export PATH="$HOME/.emacs.d/share/cask/bin:$PATH"
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs-snapshot wl-beta ddskk howm
  - cask --debug
script:
  - make
  - make clean
  - make distclean
