language: generic
env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  allow_failures:
    - env: EMACS=emacs-git-snapshot-travis
before_install:
  - ln -s $TRAVIS_BUILD_DIR ~/.emacs.d
  - export PATH="$HOME/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS
  - evm use $EVM_EMACS
script:
  - evm use $EVM_EMACS
  - make
  - make clean
  - make distclean
