language: generic
env:
  - EVM_EMACS=emacs-25.1-travis
before_install:
  - ln -s emacs ~/.emacs.d
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - sudo apt-get install -qq wl-beta ddskk
  - cask --debug
script:
  - make
  - make clean
  - make distclean
