language: emacs-lisp
cache:
  - apt: true
  - http: false
env:
  - EMACS=emacs23
  - EMACS=emacs24
  - EMACS=emacs-snapshot
matrix:
  allow_failures:
    - env: EMACS=emacs23
before_install:
  - ln -s $TRAVIS_BUILD_DIR/emacs.d $HOME/.emacs.d
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq install-info
  - sudo apt-get install -qq skkdic
  - sudo apt-get install -qq $EMACS
script:
  - cd $HOME/.emacs.d
  - make
  - make recompile EMACS=$EMACS
  - make clean
  - make distclean
