language: generic
dist: trusty
sudo: required
env:
  matrix:
    - EMACS=emacs25
    - EMACS=emacs-snapshot
before_install:
  - ln -s $TRAVIS_BUILD_DIR ~/.emacs.d
  - export PATH="$HOME/.emacs.d/share/cask/bin:$PATH"
  - if [ x"$EMACS" == x"emacs25" ]; then
    sudo apt-add-repository -y ppa:adrozdoff/emacs &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq emacs-25 emacs25-el wl-beta ddskk howm ;
    fi
  - if [ x"$EMACS" == x"emacs-snapshot" ]; then
    sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq emacs-snapshot emacs-snapshot-el wl-beta ddskk howm;
    fi
  - CASK_EMACS=$EMACS cask --debug
script:
  - make EMACS=$EMACS
  - make clean
  - make distclean
