language: generic
dist: trusty
env:
  matrix:
    - EVM_EMACS=emacs-25.2-travis
before_install:
  - ln -s $TRAVIS_BUILD_DIR ~/.emacs.d
  - export PATH="$HOME/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS
  - evm use $EVM_EMACS
script:
  - evm use $EVM_EMACS
  - make
  - make distclean
