language: generic
env:
  - EVM_EMACS=emacs-25.1-travis
before_install:
  - ln -s $TRAVIS_BUILD_DIR ~/.emacs.d
  - export PATH="$HOME/.emacs.d/share/cask/bin:$PATH"
  - sudo mkdir -p /usr/local/evm
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use --skip
  - sudo apt-get install -qq wl-beta ddskk
  - cask --debug
script:
  - make
  - make clean
  - make distclean
