language: emacs-lisp
cache:
  - apt: true
  - http: true
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq ${EMACS} ${EMACS}-el
  - sudo apt-get install -qq wl-beta ddskk
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
script:
  - make EMACS=${EMACS}
  - make clean
  - make distclean
