language: emacs-lisp
cache:
  - apt: true
  - http: true
env:
  - EMACS=emacs23
  - EMACS=emacs24
  - EMACS=emacs-snapshot
matrix:
  allow_failures:
    - env: EMACS=emacs23
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnutls-bin
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq skkdic
  - sudo apt-get install -qq zsh
  - sudo apt-get install -qq $EMACS
script:
  - make
  - make recompile EMACS=$EMACS
  - make clean
  - make distclean
