language: emacs-lisp
cache:
  - apt: true
  - http: false
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - mkdir -p $HOME/.emacs.d/
  - ln -s $TRAVIS_BUILD_DIR/* $HOME/.emacs.d/
  - ln -s $TRAVIS_BUILD_DIR/.git $HOME/.emacs.d/.git
  - export PATH="/home/travis/.emacs.d/modules/cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnutls-bin
  - sudo apt-get install -qq install-info
  - sudo apt-get install -qq skkdic
script:
  - cd $HOME/.emacs.d
  - ls -la 
  - make all EMACS=$EVM_EMACS
  - make recompile EMACS=$EVM_EMACS
  - make clean
  - make distclean
