sudo: false
language: emacs-lisp
cache:
  directories:
    - $HOME/local
env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$PATH
  matrix:
    # Debian 8
    - EVM_EMACS=emacs-24.4-travis
    # Debian 9
    - EVM_EMACS=emacs-24.5-travis
    # Debian unstable
    - EVM_EMACS=emacs-26.1-travis
    - EVM_EMACS=emacs-git-snapshot-travis
before_script:
  - sh .travis-ci/install-evm.sh $EVM_EMACS
script:
  - emacs --version
  - make EMACS=emacs
  - make clean
  - make distclean
